{% set version = "0.3-8196" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-spatialpack
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/SpatialPack_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/SpatialPack/SpatialPack_{{ version }}.tar.gz
  sha256: 9027e1656db97b721a12f5eda46532c6a99b4a079299b8d12fb57d445b237b4d

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-fastmatrix
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-fastmatrix

test:
  commands:
    - $R -e "library('SpatialPack')"           # [not win]
    - "\"%R%\" -e \"library('SpatialPack')\""  # [win]

about:
  home: http://spatialpack.mat.utfsm.cl
  license: GPL-3.0-only
  summary: 'Tools to assess the association between two spatial processes. Currently, several methodologies are implemented: A modified t-test to perform hypothesis testing about the independence between the processes, a suitable nonparametric correlation coefficient, the codispersion coefficient, and an F test for assessing
    the multiple correlation between one spatial process and several others. Functions for image processing and computing the spatial association between images are also provided. SpatialPack gives methods to complement methodologies that are available in geoR for one spatial process.'
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - xhochy

# Package: SpatialPack
# Version: 0.3-8
# Date: 2019-07-31
# Title: Tools for Assessment the Association Between Two Spatial Processes
# Description: Tools to assess the association between two spatial processes. Currently, several methodologies are implemented: A modified t-test to perform hypothesis testing about the independence between the processes, a suitable nonparametric correlation coefficient, the codispersion coefficient, and an F test for assessing the multiple correlation between one spatial process and several others. Functions for image processing and computing the spatial association between images are also provided. SpatialPack gives methods to complement methodologies that are available in geoR for one spatial process.
# Authors@R: c(person("Felipe", "Osorio", role = c("aut", "cre"), email = "felipe.osorios@usm.cl"), person("Ronny", "Vallejos", role = "aut", email = "ronny.vallejos@usm.cl"), person("Francisco", "Cuevas", role = "ctb"), person("Diego", "Mancilla", role = "ctb"))
# Author: Felipe Osorio [aut, cre], Ronny Vallejos [aut], Francisco Cuevas [ctb], Diego Mancilla [ctb]
# Maintainer: Felipe Osorio <felipe.osorios@usm.cl>
# Depends: R (>= 2.10)
# Imports: stats, graphics
# License: GPL (>= 2.0)
# URL: http://spatialpack.mat.utfsm.cl
# LazyLoad: yes
# NeedsCompilation: yes
# Packaged: 2019-07-31 19:11:14 UTC; felipe
# Repository: CRAN
# Date/Publication: 2019-07-31 21:50:05 UTC
