appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: n4+U6FblT92of7Gnx+MHmZBfYCtRNFrcnYBK7rTnqxtmv6mCQsya/JGS2YJCF3M75Jvn16cT0xW7+2n0gF4vX0Qj7zqzn2lsICbCZFh3yYmfT29FVXn3OD3i7s5VvO4YBct83oRHlfOV2Xi0+u01yoJIFIryE7FBHPmVViZrziruX7T3JR1D7e2pAdWCdy4as6nGaHNl7ekBwuj6SpUURMjgUCO+jF5zsyP5V5gMFtngWhMTagHe9Nyn4E+6sDK82OsYuWpRQvctxgeyCG2XKBPDW4Jhs+j7zgPwXV7srxJYrTC/SGaQBt6MRoRGVVZJlImA2f0N0wd0TNM2p9G02c6S/podVuXrLrDvHD7XKV5RCjZhZFnLMSBGgngXLwZniiOXKmLQv5SPAUbARw9dA2SNz5ZlgmsFLZ7buE6s9fkuSUhWT23gdPbdJ+ySWE/86wW3/9C/SNptmCD79XVZyWjCrcRsXL2sDVtUlhc7/w2CXGYzRpHV1u0i2SloUjZlRdGiUq348UeTyFQpw2NBavQnY5kb6z4BqYis7ezzS81aL/JyVgMAbtbm7bYoTfZ20KcfEQXvVRgYMM/r/9bRzz3qQgH/7v9QMDxjwJACe7ReY2JPS6PP7FkjhWnMC8OTuhpJRKBa0u9XDiabxe8KmFjiULyczqWqXCDRyhNrYZg=
conda_forge_output_validation: false
